import Head from "next/head";
import DefaultLayout from "@/components/layout/default";
import Home from "@/components/Home/Home";

export default function HomePage() {
    return (
        <DefaultLayout>
            <div>
                <Head>
                    <title>S_Comm Shopping Mall</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.svg" />
                </Head>

                <main>
                    <Home />
                </main>
            </div>
        </DefaultLayout>
    );
}
